### ISSUE TITLE
HTML Source editing disabled

### ISSUE THREAD

**Issue by tpolischuk** [Annotum/Annotum#225]
Hello, 
We are currently trying to upgrade to Annotum 2.0 and in QA we noticed that HTML editing from articles has been disabled. We have had several instances where editing the source of an article to fix odd things submitted by authors that is not possible from the regular rich editor. Is there a way to re-enable the editing of the source? 
Thank you

**Comment by carlthewebmaster** [comment]
There's an "Anno Source" button:
![image](https://cloud.githubusercontent.com/assets/294757/6781501/80c43be2-d144-11e4-86f6-aa0a73565796.png)

That brings up a code editor:
![image](https://cloud.githubusercontent.com/assets/294757/6781496/79729938-d144-11e4-9a05-d228a19fc171.png)

Do you not see that editing control?

**Comment by tpolischuk** [comment]
Ah ok yes I totally missed that. I thought it was just a validator. Thank you!
