### ISSUE TITLE
Theme error

### ISSUE THREAD

**Issue by tjl666** [Annotum/Annotum#227]
Hi there,
Just installed the latest version of your base theme and when I go to add/edit an article the Abstract box show the following error

Fatal error: Class 'XSLTProcessor' not found in /home/selfcarejournalt/public_html/wp-content/themes/annotum-base/functions/tinymce.php on line 1003

Many thanks

**Comment by carlthewebmaster** [comment]
This error indicates that you do not have the [XSLT extension](http://php.net/manual/en/book.xsl.php) installed on your server.  This server component is required to use Annotum 2.0.

Here are some [brief instructions](http://annotum.uservoice.com/knowledgebase/articles/418717) for installing it on Ubuntu/Apache2.

**Comment by tjl666** [comment]
Thank you for this, now updated and working :)

**Comment by gyne** [comment]
Hi,

I also have this same issue but my hosting is a shared one on GoDaddy. I cannot have root access to make modifications. What do I do?

**Comment by carlthewebmaster** [comment]
You need to contact GoDaddy support and ask for the component to be installed, using information in the link above.
