### ISSUE TITLE
WP 4.4 compatibility

### ISSUE THREAD

**Issue by profnimrod** [Annotum/Annotum#237]
Has anyone confirmed compatibility with WP 4.4. yet?

**Comment by carlthewebmaster** [comment]
Based on my limited testing I don't see any major issues.

**Comment by jobdiogenes** [comment]
I try latest github version with latest WordPress (4.4.1)  but, Editor are not working and translation appear incomplete.  Testing under Debian Jessie.
Some errors in apache error.log.  XSLTProcessor::transformToXml(): No stylesheet associated to this object in /var/www/html/wordpress/wp-content/themes/Annotum-master/annotum-base/functions/tinymce.php on line 1022, referer: http://10.1.0.8/wordpress/wp-admin/edit.php?post_type=article&ids=4

**Comment by alex-wreschnig** [comment]
Have run into the same issues @jobdiogenes ran into. The theme installs fine, but the editor is not working. Error text is similar. Renders Annotum largely unusable.

**Comment by carlthewebmaster** [comment]
I will try to look into this in the coming days. Sorry for the inconvenience!

**Comment by carlthewebmaster** [comment]
Actively working on a fix that I hope will restore editor functionality
with WP 4.6+. Work in progress.

-- 
_______________________
Carl Leubsdorf, Jr.
Solvitor ► Problem Solved.

**Comment by carlthewebmaster** [comment]
OK. [This version](https://github.com/Annotum/Annotum/releases/download/v2.1.1/annotum-base211.zip) _should_ work with WP versions up to 4.4.4.

**Comment by carlthewebmaster** [comment]
I'm going to call this fixed for 4.4.4. See #241 for annotum compatibility with WP v4.5+
