### ISSUE TITLE
Feature proposal: Support for double blind peer review

### ISSUE THREAD

**Issue by nasoultanidis** [Annotum/Annotum#238]
**Thank you for your hard work! The theme works surprisingly well out of the box!**

A small feature proposal you might want to consider:
Currently reviewers are able to see the author names of articles they review. It might be beneficial for some use cases to hide the author names.

Additionally, contributors (authors) are able to see all articles, not only their own or articles they are assigned to review. A checkbox to restrict this behaviour might be also interesting.

Similar suggestions have been made in this very good overview:
http://tkbr.ccsp.sfu.ca/bits/occam-FINAL.pdf

**Comment by carlthewebmaster** [comment]
Thanks for the suggestions.

>  It might be beneficial for some use cases to hide the author names.

As a workaround, you could have the author use an alias account to create the article, then modify the authorship after review but prior to publishing.

> contributors (authors) are able to see all articles, not only their own or articles they are assigned to review. A checkbox to restrict this behaviour might be also interesting.

This is a setting in Appearance | Annotum Settings (scroll to bottom):
![image](https://cloud.githubusercontent.com/assets/294757/11877534/e3082636-a4bd-11e5-884f-d527c27d4376.png)

I thought the default was "Yes", but it sounds like it is set to "No" on your site.

**Comment by nasoultanidis** [comment]
Thank you, Carl!
I will try your work-around proposal.
Concerning the second issue, that was bad. I did not fully understand that option.

When I make a video walkthrough, I'll be sure to link to the annotum.org website. The project is a bit underrepresented on youtube.

**Comment by carlthewebmaster** [comment]
No worries.  Meanwhile, please get in touch (@annotum on Twitter is perhaps easiest) as I would like to know more about your journal, videos, etc.
