### ISSUE TITLE
TinyMCE not loading on article authoring page

### ISSUE THREAD

**Issue by devinberg** [Annotum/Annotum#239]
Running Wordpress 4.4 I am getting blank text entry boxes on the article authoring window. Unable to type or switch to raw text entry mode. Some comments on it here: https://twitter.com/devinberg/status/681674572526129153

Seeing similar problems in Chrome, Firefox, and Microsoft Edge. Getting the following errors when monitoring JS console.

In Chrome and Firefox:
```
Error: Syntax error, unrecognized expression: &lt;div data-textorum-nsurl=&quot;http://www.w3.org/XML/1998/namespace&quot; data-textorum-nsprefix=&quot;xml&quot;&gt;&lt;/div&gt;&amp;lt;div data-textorum-nsurl=&quot;http://www.w3.org/XML/1998/namespace&quot; data-textorum-nsprefix=&quot;xml&quot;&amp;gt;&amp;lt;/div&amp;gt;&amp;lt;div class=&quot;p&quot; data-xmlel=&quot;p&quot;&amp;gt; &amp;lt;/div&amp;gt;
```

In MS Edge:
```
SCRIPT5007: Unable to get property 'documentElement' of undefined or null reference
editor_plugin.js (34,6576)
```

**Comment by carlthewebmaster** [comment]
Are you using release 2.1 of annotum?

https://github.com/Annotum/Annotum/releases/tag/v2.1

If not you'll want the annotum-base.zip from there.

**Comment by devinberg** [comment]
You were right. I was using 2.0. Updating to 2.1 fixed the issue. Thanks.
