### ISSUE TITLE
Where is my comment?

### ISSUE THREAD

**Issue by Gitubert** [Annotum/Annotum#245]
I have submitted a comment on Annotum, but it seemed to be removed! I am just wondering why? 
What would be the problem with? 
I was simply suggesting some features for the theme. Is it not allowed to make suggestions?
Weird!

**Comment by carlthewebmaster** [comment]
Not removed. Commented and closed. And appreciated! 😄

https://github.com/Annotum/Annotum/issues/244

**Comment by Gitubert** [comment]
Well, but why it was closed? And what does this mean?
Will the previous suggestions be taken into consideration or should I see with a developer in a developing country to customize another theme to my needs? To be frank, I appreciated Annotum but in its current functionalities, it does not answer my needs at all. Indeed, it is unsuitable for a professional usage or serious journals but it fits a blog or narrative tales more than authoritative scientific journal, though it does not need much to be a professional tool! 
As there is an ‘**Annotum Base**’, it might be good to see ‘**Annomum Pro**’ with more functions for professional use and serious production!
With some tweaks and new functions, it could be much improved and adapted to professional-like journal. So, if I may, I suggest to the author to build a boosted and paid version of his theme (for e.g., as Annotum Pro) with good support behind. A Pro version should come with more functionality, flexibility and end-user goals to be used for a real and professional journal taking into account the new open access trend.   
So, here is a reformulation of my previous comment with new suggestions for potential Pro version of the theme, should the author be tempted to launch one affordable paid version:
- Be fully compatible with other plugins or, alternatively, it should have all the required functions for managing and handling submissions and publications: so far, I tested many popular plugins but they were not working at all in Annotum, which is a huge downside of the theme particularly the theme does not offer all the required functionalities for the full management of a journal to eventually avoid the use of any third party plugins. In other words, Annotum should either be either standalone journal software with complete journal and manuscript management systems, so it does not matter much if other plugins do not work with it. Or, it should be compatible with third party plugins to enrich its missing functions; otherwise it does not answer the basics needs of people who wish to build respectable and serious journals. If the author opts to develop a paid Pro version, it is expected that such a version should contain all the advanced functions required to manage submissions and article status from submission to the final phase of production online. The theme’s author may need to integrate in his theme similar functions to those provided by a plugin called ‘WP Abstract and manuscript’:
https://wordpress.org/plugins/wp-abstracts-manuscripts-manager/
As such, authors could be able to submit manuscripts by uploading PDF, images or Doc files through a simple submission form including fields for names, affiliation, country, and options to upload manuscript files (PDF, doc, figures….). The current version of Annotom does not allow this.     
- It should be a fully responsive theme to adapt to multiple internet-content reading devices. All themes and webpages are switching to responsive designs now…  
- Fully compatible with RTL languages and UTF8 (or UTF9) encoding. 
- The current built-in PDF file is very poor, and rather childish! Such an important function should be optimized to generate professional-look or at least acceptable PDF format. Alternatively, there should be an option or a function to upload PDF files created with other PDF creators. So, the admin could build PDF documents locally with tools of his choice, and then link them or upload them in a similar way to uploading media or images to articles. 
- Possibility to add co-authors by the admin during the final copyediting or typesetting stage: for example a button of key of “Add author” to this article (including names, affiliation, country…), should be available under the field “Article title”. Currently, it is not possible to add authors if they are not already registered as users! This is an aberration to software deetcsigned to handle and manage multi-authored manuscripts! Adding authors or coauthors should be easy and doable at the moment of writing or publishing the article, in addition, of course, to be able to select from the list of registered users or authors.
The author names should appear under the title alongside the date. Ideally, this should be customizable: the admin could be able to choose to display or hide authors in the excerpts, just beside the dates.      
- Be more flexible and customizable for article submission and management (for e.g., article status: under review, accepted, rejected, author notification with each change of status...etc.).
- Be customizable to set up any type of citation style defined by the admin but not imposed by the theme only (the current citation format is amateurish and unprofessional): the admin should be able to define the style of citation s/he wants for his or her journal and to be able to insert or delete any element from the citation style. For example, a journal manager should be able to set up a citation format by the author’s name, journal, title, date, or any other desirable formats of variants.
- It should be there some static and dynamic place for banners, sliders and sponsorship links or customizable messages on the home page! Again, the admin should be able to display or hide such elements. 
In short, a good theme should be highly and easily customizable, functionality-rich, flexible and evolutive to adapt with current and future web tools and trends. The more it will be easy, professional, flexible and customizable, the more it would be appreciated and adopted by a large community of users.  
I think that such optimizations and others should be extremely easy to be done by the theme’s author because s/he knows his/her theme much better than any other guy. I do not think that fixing such issues would take more than tens of minutes at maximum.
Finally, and again, alongside ‘Annotum Base’, it might be good to see ‘**Annomum Pro**’ (as premium theme) for more professional and serious journals. If such version will be available soon, I'll be the first to purchase it ($50-$100).

Hopefully this might be useful!

**Comment by Gitubert** [comment]
As we are in, here is what I get when clicking on XML and PDF links:
**"Page Not Found
Sorry, we’re not sure what you’re looking for here."**
Appeared to both requests (PDF and XML).
It might be better not to have these functions than to offer poor functions of them.

**Comment by carlthewebmaster** [comment]
Regarding the XML/PDF not found error, this is a [known issue](https://github.com/Annotum/Annotum/issues/243). The workaround is to change the permalinks settings to something other than the default. (And as noted in #243, you can even change it back to the default; the PDF/XML links will work.).

**Comment by carlthewebmaster** [comment]
Regarding the long list of suggestions and possible enhancements, again, thank you for your enthusiastic input!  The suggested improvements are very extensive, and also get away somewhat from the design goals of Annotum:

- Dead-simple workflow
- WYSIWYG editing with full XML validation and valid JATS-XML output
- Rely on as much WordPress functionality as possible
- Pleasant design

If you are looking for a more commercially-oriented tool for publishing journals (with banners, subscriptions, custom citation formats, etc.) you may want to look at PKP's Open Journal System.  It lacks some of Annotum's simplicity (and JATS-XML output), but has many of the features you describe.

> Lastly, I want to comment I think that such optimizations and others should be extremely easy to be done by the theme’s author because s/he knows his/her theme much better than any other guy. I do not think that fixing such issues would take more than tens of minutes at maximum.

Thanks so much for the compliment, but I have to tell you that this estimate is nowhere close to the reality of WordPress (or really any software) development.  I could easily see the listed features taking many hundreds of hours, perhaps as many as 1,000 when considering design, coding, and testing.

Annotum is open source software, so we aren't in the business of building and selling software licensing.  And even if we were, to date all major development has been funded by interested parties.  Adding the features you describe is certainly possible, but would require significant funding to make it a reality.  

> Well, but why it was closed? And what does this mean?

For the Annotum project, we use the Github issue tracker for tracking and responding to specific issues with the software code itself (bugs), but we prefer not to use this for new feature requests which are in a somewhat different group and handled differently by the Annotum team.  We're sorry if this was not clear.  For reference, please see the [Annotum Support](https://annotum.org/support/) page, a portion of which is reproduced here:

> ## Annotum Help and Support

> For articles and screen shots showing how to use Annotum, please visit the [Annotum Knowledge Base](https://annotum.uservoice.com/knowledgebase).

> For questions on how to use Annotum, to report problems, or to submit feedback, please use the [Annotum Help Desk](https://annotum.uservoice.com/).

> For specific technical questions or bug reports regarding the Annotum Theme and any included software code, please use the [GitHub Issue Tracker](https://github.com/Annotum/Annotum/issues).

You can also make suggestions on the [Support site forum](https://annotum.uservoice.com/forums/141029-general).

We absolutely welcome user requests, suggestions, and other input, and consider them carefully.

Once again, thank you for your thoughtful and detailed suggestions.

Closing this ticket as "resolved, won't fix" (but thanks!).
