### ISSUE TITLE
Publishing from "Quick Edit" does not publish properly

### ISSUE THREAD

**Issue by profnimrod** [Annotum/Annotum#253]
Firstly I upload an article from XML.  I make a few changes using "Quick Edit", including changing it's status to Published.  If I switch to the same article via the full Edit, it's status is shown as Draft.  Is this intended functionality?

**Comment by carlthewebmaster** [comment]
Possibly same issue as #236 ?

**Comment by carlthewebmaster** [comment]
Not intended. I suspect you'll have to go into the full editor to make the change.

**Comment by carlthewebmaster** [comment]
Last comment: I would very much avoid publishing via quick edit.  There is code that fires on publish that probably does not fire when status is changed via quick edit.

**Comment by profnimrod** [comment]
Sorry for the duplication Carl - looks like I do even created the original [😉]


________________________________

**Comment by carlthewebmaster** [comment]
Duplicates #236
