### ISSUE TITLE
Annotum Base Template article is not working in wordpress 4.8

### ISSUE THREAD

**Issue by pankajatil** [Annotum/Annotum#256]
I'm trying to develop a project using Annotum Base Template in WordPress 4.8 in Article section I can add an article, subtitle of the article, and abstract but an editor for Article is missing also I'm not getting anything on reference tab. can anyone help me in this.
Kindly see prnt scrn.
![issue](https://user-images.githubusercontent.com/29862235/27792190-300be91c-6016-11e7-964d-c58c2b77ff78.png)
![issue1](https://user-images.githubusercontent.com/29862235/27792191-3011ac62-6016-11e7-9eb8-29070b1aa85e.png)

**Comment by carlthewebmaster** [comment]
Per #241, Annotum only works up to WP 4.4.5, and only if you use the very latest version of Annotum, [v2.1.1.1](https://github.com/Annotum/Annotum/releases/tag/v2.1.1.1).

**Comment by pankajatil** [comment]
Tried But yet not working.
